### PR TITLE
Fix does subexpression expanded from body have type defined after macro

### LINKED ISSUE #85: Maki does not properly handle expansion types defined after macro using a typedef
Given the following example:
```c
#define CAST_TO_MYINT(x) ((MYINT) (x))

typedef int MYINT;

int main(void) {
        int x = 5;
        MYINT y = CAST_TO_MYINT(x);

        return 0;
}
```

Maki produces the following output:
```json
  {
    "Kind": "Invocation",
    "Name": "CAST_TO_MYINT",
    "DefinitionLocation": "/home/joey/merc/test/typedef_issue.c:1:9",
    "InvocationLocation": "/home/joey/merc/test/typedef_issue.c:7:12",
    "ASTKind": "Expr",
    "TypeSignature": "int CAST_TO_MYINT(int x)",
    "InvocationDepth": 0,
    "NumASTRoots": 1,
    "NumArguments": 1,
    "HasStringification": false,
    "HasTokenPasting": false,
    "HasAlignedArguments": true,
    "HasSameNameAsOtherDeclaration": false,
    "IsExpansionControlFlowStmt": false,
    "DoesBodyReferenceMacroDefinedAfterMacro": false,
    "DoesBodyReferenceDeclDeclaredAfterMacro": false,
    "DoesBodyContainDeclRefExpr": false,
    "DoesBodyEndWithCompoundStmt": false,
    "DoesSubexpressionExpandedFromBodyHaveLocalType": false,
    "DoesSubexpressionExpandedFromBodyHaveTypeDefinedAfterMacro": false,
    "DoesAnyArgumentHaveSideEffects": false,
    "DoesAnyArgumentContainDeclRefExpr": true,
    "IsHygienic": true,
    "IsICERepresentableByInt16": false,
    "IsICERepresentableByInt32": false,
    "IsDefinitionLocationValid": true,
    "IsInvocationLocationValid": true,
    "IsObjectLike": false,
    "IsInvokedInMacroArgument": false,
    "IsNamePresentInCPPConditional": false,
    "IsExpansionICE": false,
    "IsExpansionTypeNull": false,
    "IsExpansionTypeAnonymous": false,
    "IsExpansionTypeLocalType": false,
    "IsExpansionTypeDefinedAfterMacro": false,
    "IsExpansionTypeVoid": false,
    "IsExpansionTypeFunctionType": false,
    "IsAnyArgumentTypeNull": false,
    "IsAnyArgumentTypeAnonymous": false,
    "IsAnyArgumentTypeLocalType": false,
    "IsAnyArgumentTypeDefinedAfterMacro": false,
    "IsAnyArgumentTypeVoid": false,
    "IsAnyArgumentTypeFunctionType": false,
    "IsInvokedWhereModifiableValueRequired": false,
    "IsInvokedWhereAddressableValueRequired": false,
    "IsInvokedInSizeOf": false,
    "IsInvokedWhereICERequired": false,
    "IsInvokedWhereConstantExpressionRequired": false,
    "IsAnyArgumentExpandedWhereModifiableValueRequired": false,
    "IsAnyArgumentExpandedWhereAddressableValueRequired": false,
    "IsAnyArgumentExpandedInSizeOf": false,
    "IsAnyArgumentConditionallyEvaluated": false,
    "IsAnyArgumentExpandedWhereConstExprRequired": false,
    "IsAnyArgumentNeverExpanded": false,
    "IsAnyArgumentNotAnExpression": false
  }
```

Maki does not correctly output that the typedef for the expansion type is defined after the macro: `IsExpansionTypeDefinedAfterMacro` should be set for this case.

Note that an example with a user-defined type like a pointer to a struct does not trigger this issue.

### PR DESCRIPTION
**Pull request by PappasBrent**
Previously, Maki would fail to report when a macro contained a subexpression whose body references a typedef'd type defined after the macro was defined. This was due to two oversights: Maki would only consider desugared typed when checking type-related predicates, and would not check certain expressions that contain direct type name such as explicit cast expressions and compound literal expressions. This PR fixes these issues and updates the relevant test cases to reflect the new expected behavior.

This PR also generally reworks the type predicate-checking API to be more robust and concise.

Closes #85

### CODE REVIEW

**Comment by PappasBrent** [comment]
I realized this change does not recursively check typeof types for typedef types, so I am marking this PR as a draft until I add support for this (should be done by this afternoon).

**Comment by PappasBrent** [comment]
I ended up reworking much of the type predicate checking API with this change. The resulting code should be more robust and concise, and passes all test cases.

File: lib/ASTUtils.cc [hunk 1]
```diff
@@ -10,114 +9,101 @@
...
+    auto DFLoc = DLoc.isValid() ? SM.getFileLoc(DLoc) : clang::SourceLocation();
 
-        return !DCtx->isTranslationUnit();
-    });
+    return DFLoc.isValid() && SM.isBeforeInTranslationUnit(L, DFLoc);
 }
 
-bool hasTypeDefinedAfter(const clang::Type *T, clang::ASTContext &Ctx,
-                         clang::SourceLocation L, bool IgnoreTypedefs) {
+bool isAnyDeusgaredTypeDefinedAfter(const clang::Type *T,
```
Comment (SilverMight) [inline lib/ASTUtils.cc]: should this be `isAnyDesugaredTypeDefinedAfter` ?

File: lib/ASTUtils.cc [hunk 2]
```diff
@@ -10,114 +9,101 @@
...
-                    return SM.isBeforeInTranslationUnit(L, DFLoc);
-                }
+    while (T) {
+        if (T->isArrayType()) {
+            T = T->getBaseElementTypeUnsafe();
+        } else if (T->isAnyPointerType()) {
+            T = T->getPointeeType().getTypePtrOrNull();
+        } else if (auto ET = clang::dyn_cast<clang::ElaboratedType>(T)) {
+            T = ET->desugar().getTypePtrOrNull();
+        } else if (auto TT = clang::dyn_cast_or_null<clang::TagType>(T)) {
```
Comment (SilverMight) [inline lib/ASTUtils.cc]: Is there a reason `dyn_cast_or_null` is used here - I wasn't sure what it did and it seems like [it is deprecated](https://llvm.org/doxygen/namespacellvm.html#a5f6182886dc2f96c204299e92c1565d5) and forwards to `dyn_cast_if_present` which is just able to handle nullptr as an argument, not that it actually returns null.

I think the rest of the invocations use it correctly, I just assumed `T` can't be null here

File: lib/ASTUtils.cc [hunk 3]
```diff
@@ -10,89 +9,101 @@
 #include <clang/Basic/SourceLocation.h>
 #include <clang/Basic/SourceManager.h>
 #include <functional>
+#include <llvm-17/llvm/Support/raw_ostream.h>
```
Comment (SilverMight) [inline lib/ASTUtils.cc]: Doesn't look like this is used:
```suggestion
```

**Review by SilverMight — CHANGES_REQUESTED** [review]
LGTM besides comments - I like moving a lot of the shared AST logic into `ASTUtils` :)

Also, I think it may be worth considering using something like `clang::TypeVisitor` where possible instead of long if-else chains dyn-casting on the type, but that can be a future change. I saw this mentioned in the [LLVM programmer manual](https://llvm.org/docs/ProgrammersManual.html#the-isa-cast-and-dyn-cast-templates) and it seems like it may be more efficient as it switches over the type class. Might not be worth the trouble though.

File: lib/ASTUtils.cc (hunk 1 above)
Comment (PappasBrent) [reply lib/ASTUtils.cc]: Oops, thanks for catching that typo

File: lib/ASTUtils.cc (hunk 2 above)
Comment (PappasBrent) [reply lib/ASTUtils.cc]: `dyn_cast` suffices here; I used `dyn_cast_or_null` because I had copied and pasted it from another function definition. I won't change the existing uses to `dyn_cast_or_present` but will use that going first, thanks for finding out that `dyn_cast_or_null` is deprecated.

File: lib/ASTUtils.cc (hunk 3 above)
Comment (PappasBrent) [reply lib/ASTUtils.cc]: Yeah I had included the header for debugging but forgot to remove it afterward; thanks.

**Comment by PappasBrent** [comment]
I've addressed the immediate issues in the comments and will open a PR later for replacing the type-checking if-else chains with `clang::TypeVisitor` and to replace all calls to `dyn_cast_or_null` with `dyn_cast_if_present`.

**Review by SilverMight — APPROVED** [review]
