### PR TITLE
Fix property checks for paren exprs

### LINKED ISSUE #62: Maki does not correctly identify some properties for macros expandeding to `ParenExpr`s
Maki incorrectly identifies some properties as false for macros that expand to parenthesized expressions.
For example, for the following code:

```c
#define WRAP(x) (x)
#define ID(x) x

int main(void) {
    int x;
    &WRAP(x);
    &ID(x);
    return 0;
}
```

Mak reports the `IsInvokedWhereAddressableValueRequired` property for the invocation of `WRAP()` as `false`, when it should be set to `true`.
Maki correctly reports the property for invocation of `ID()`, however.
Maki should correctly report properties for aligned, non-nested macro expansions, regardless of whether or not they are wrapped in a parenthesized expression.

### PR DESCRIPTION
**Pull request by PappasBrent**
Removes the `skipImplicitAndParens()` function so that Maki can accurately check the `Addressable` and `Modifiable` properties for macros whose definitions wrap their bodies and/or arguments in parenthesized expressions.

Closes #62

### CODE REVIEW

File: lib/MakiASTConsumer.cc [hunk 1]
```diff
@@ -1057,7 +1051,7 @@ void MakiASTConsumer::HandleTranslationUnit(clang::ASTContext &Ctx) {
                         // not expanded from the body of the same macro
                         if (!ExpandedFromBody(U)) {
                             auto Operand = U->getSubExpr();
-                            Operand = skipImplicitAndParens(Operand);
+                            Operand = Operand->IgnoreImplicit();
```
Comment (SilverMight) [inline lib/MakiASTConsumer.cc:1054]: Just curious, why do we only have to ignore implicit here and nowhere else?

Comment (PappasBrent) [reply lib/MakiASTConsumer.cc:1054]: Honestly it doesn't matter if we call `ignoreImplicit()` here or not, since the following call to `inTree()` will return the same in either case since were just skipping implicit exprs and the matcher for arguments doesn't match on implicit exprs anyway. I chose to keep it pretty much arbitrarily (not sure keeping it or not has any effect on performance).
