### PR TITLE
Fix macro validity checks

### LINKED ISSUE #48: Maki incorrectly reports valid macros as invalid
Maki currently reports some macros with valid source locations as having invalid source locations, and does not emit properties for them when the `--no-invalid-macros` flag is turned on.

For instance, consider the following code:

```c
#if !defined(RL_IM_INSERT)
#define RL_IM_INSERT 1
#define RL_IM_OVERWRITE 0
#
#define RL_IM_DEFAULT RL_IM_INSERT
#endif

int main() {
    int a = RL_IM_DEFAULT;
}
```

If the `--no-invalid-macros` is turned on, then Maki emits no properties for the nested invocation of `RM_IM_INSERT` (which would mostly be unreliable anyway since the macro invocation is nested but that is besides the point).
Maki should treat such macro invocations as valid and emit properties for them.

### PR DESCRIPTION
**Pull request by PappasBrent**
- Refactor the definitions for `shouldSkipMacroDefinition()` and `shouldSkipMacroInvocation()` to be easier to read and debug.
- Fix the call to `shouldSkipMacroInvocation()` by passing the spelling location of macro expansions' begin locations to handle nested expansions correctly.
- Change the expected output of tests involving nested macro expansions to reflect these changes.

Closes #48

### CODE REVIEW

File: lib/MakiFlags.cc [hunk 1]
```diff
@@ -7,21 +7,47 @@ namespace maki {
...
+    if (!Flags.ProcessBuiltinMacros && MI->isBuiltinMacro()) {
+        return true;
+    }
+    auto DefinitionLocation = MI->getDefinitionLoc();
+    if (!Flags.ProcessMacrosInSystemHeaders &&
+        SM.isInSystemHeader(DefinitionLocation)) {
+        return true;
+    }
+    if (!Flags.ProcessMacrosAtInvalidLocations) {
+        [[maybe_unused]] auto [Valid, LocationOrError] =
```
Comment (SilverMight) [inline lib/MakiFlags.cc]: Very minor but I think it'd be more appropriate to use `std::tie` and `std::ignore` instead of `[[maybe_unused]]` attribute especially because LocationOrError is always unused

**Review by SilverMight — APPROVED** [review]
